# Generated by Django 5.0 on 2026-01-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
