# Generated by Django 6.0.1 on 2026-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_id_alter_room_id_alter_userstatus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='room_avatars/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
