# Generated by Django 6.0.1 on 2026-02-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_room_avatar_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
