# Generated by Django 6.0.1 on 2026-02-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
